const dadosEscola = {
       integral: {
            "1º A": [
                        "ANA BEATRIZ CABRAL DA SILVA",
                        "ANA BEATRIZ DANTAS BERNARDO",
                        "ANA BEATRIZ OLIVEIRA SERRA",
                        "ANA CAROLYNA CARNEIRO SOUSA",
                        "ANA JULIA DAS CHAGAS VIEIRA",
                        "ANA LUIZA DE SOUSA LOURENCO",
                        "DEBORA IOLANDA GOMES DA SILVA",
                        "DEVIDSON RAMOS DE OLIVEIRA",
                        "DIOGO SANTOS FERREIRA",
                        "ERICK SANTOS ARAUJO",
                        "FERNANDO ERLANIO DE OLIVEIRA AGUIAR",
                        "JESSICA DEBORA SILVA OLIVEIRA",
                        "JOAO GABRIEL SOUSA RODRIGUES",
                        "JOAO LUCAS SOUSA DA COSTA",
                        "JORGE MIGUEL ARAUJO LOPES",
                        "JULIA EVELLEN PAIVA DA SILVA",
                        "KAILANY DA SILVA COSTA",
                        "KAROLLAINY OLIVEIRA SOUSA",
                        "KAUA ARAUJO MENDES",
                        "LUIS GUSTAVO COSTA FERNANDES",
                        "LUIZ DAVI OLIVEIRA FIDELE DE JESUS",
                        "MARIA ALICIA CARVALHO NUNES",
                        "MARIA CLARA DA CRUZ SILVA",
                        "MARIA EDUARDA BERNARDO SOUZA",
                        "MARYA EDUARDA DOS SANTOS LOBAO",
                        "MARIA VITÓRIA RODRIGUES FREIRE",
                        "MOISES ARCANJO FLOR FERREIRA",
                        "RAYSSA DA SILVA RODRIGUES",
                        "RONNALD LOPES DE OLIVEIRA",
                        "RYAN DA SILVA COSTA",
                        "SAMUEL SANTIAGO DE LIMA",
                        "THALES GABRIEL FERREIRA DE LIMA",
                        "TIAGO TAVARES SOUZA",
                        "YANN FERREIRA SILVA COELHO",
                        "YASMIN SILVA COUTO"
            ],
            "1º B": [
                        "ALESSANDRO DOS SANTOS RODRIGUES",
                        "ANA ESTER DA SILVA FELIX",
                        "ANA RUTY PEREIRA DOS SANTOS",
                        "ARIELE DE CARVALHO GONDIM BARBOSA LEMOS",
                        "BERNARDO BATISTA LIMA",
                        "BRENO HENRIQUE CASTRO VALENTIM",
                        "DANIEL PAULINO DE ARAUJO",
                        "DAVI GOMES DIAS",
                        "DIEGO WALLACE SILVA OLIVEIRA",
                        "ESTER VIRGINIO MARIANO",
                        "FILIPE BRAS DE PAULA",
                        "FRANCISCO EDILSON OLIVEIRA ANDRADE",
                        "GABRIELA RODRIGUES DOS SANTOS",
                        "GUSTAVO NERY TEIXEIRA DE PAULA",
                        "IAN DE ABREU VIANA",
                        "JOSE MARLEY MENDES DOS SANTOS",
                        "LARA WINY SOUSA DA SILVA",
                        "LUDMILA LOPES EVANGELISTA",
                        "LUIGI LIMA DE OLIVEIRA",
                        "MARCOS VINICIUS ARAUJO LIMA ALVES",
                        "MARIA BEATRIZ TELES GUEDES DE SOUSA",
                        "MARIA GABRIELA DA SILVA MACEDO ARAUJO",
                        "MARIA ISABEL ALVES PEREIRA",
                        "MARIA ISABELLE DAMASCENO CASTRO",
                        "MARIA IZADORA SILVA SOUSA",
                        "MARIA MANUELA FERREIRA LIMA",
                        "MARIA VITORIA SANTOS DE LIMA",
                        "MIGUEL ANTONIO LOPES DA CUNHA",
                        "NATHALLY ELOAR DO SANTOS HENRIQUE DA SILVA",
                        "PAULO LUCAS VIEIRA DOS SANTOS",
                        "PEDRO LUCAS ARAUJO BRAUNA",
                        "RHUAN DE BRITO RODRIGUES",
                        "RODRIGO OLIVEIRA DA SILVA",
                        "SAULO LUKA PESSOA TABOSA",
                        "THALIA SOUSA OLIVEIRA",
                        "YURI TEIXEIRA DA SILVA"
            ],
            "1º C": [
                        "ALICE FIRMINO DOS SANTOS SILVEIRA",
                        "ANA KETHELLY AGUIAR DE SOUZA",
                        "ANA LIVIA DA CRUZ BORGES",
                        "ANA VITORIA SOUSA DE LIMA",
                        "BRIAN VALENTE DOS SANTOS",
                        "CAIO VICTOR SALES DO NASCIMENTO",
                        "CARLOS YUDI SILVA DO NASCIMENTO",
                        "CECILIA BORGES OLIVEIRA",
                        "DALILA SIMONE DOS SANTOS",
                        "ELNATAN DOS REIS RODRIGUES",
                        "FABIANO SANTIAGO DOS ANJOS",
                        "FRANCISCO MANOEL DOS ANJOS DA SILVA",
                        "GABRIEL CASTRO DE SOUSA",
                        "HELLEN MARIA DO NASCIMENTO BERNARDO",
                        "ISABELE ROCHA FERREIRA",
                        "JOAO LEVI GOMES VIEIRA",
                        "JOAO PEDRO LIMA SOARES",
                        "JOAO VITOR DE PAULO DO NASCIMENTO",
                        "JULIA NICOLY DE LIMA",
                        "JUAN CARLOS DA SILVA",
                        "KEVEN GABRIEL DE SOUSA RIBEIRO",
                        "LUCY ELEONORA DA COSTA GOMES",
                        "LUIZ OTAVIO DA SILVA MOREIRA",
                        "LUNNA DE LIMA ABREU",
                        "MARIA EDUARDA BEZERRA SANTOS",
                        "MARIA EDUARDA RODRIGUES GUIMARAES",
                        "MARIA LUIZA DA SILVA FRANCA",
                        "MARIA VITORIA DA SILVA DO NASCIMENTO",
                        "Maria Sophia Carvalho da Costa soares",
                        "PEDRO GABRIEL TABOSA ROSENO",
                        "PEDRO NICOLAS TEIXEIRA ALMEIDA",
                        "SAMUEL DO VALE DE OLIVEIRA",
                        "SAMUEL FREITAS ALVES",
                        "SARAH KELLY FERREIRA SOUSA",
                        "YAN MIQUEIAS OLIVEIRA ALVES"
            ],
            "2º A": [
                        "ANA LIVIA DOS SANTOS BARATA",
                        "ANTONIO VINICIUS ROCHA FERREIRA",
                        "CARLA SAMANTHA DE OLIVEIRA ASSARE",
                        "CLARISSE YASMIN DA SILVA EVARISTO",
                        "DEBORA CRISTINA ALVES DOS SANTOS",
                        "ENZO DOS SANTOS MONTEIRO",
                        "ERIK DOUGLAS LIMA MARTINS",
                        "GABRIEL SILVEIRA DE SANTANA",
                        "GIVANILDO INACIO DA SILVA FILHO",
                        "GUILHERMY KAUA DA SILVA FERREIRA",
                        "IRVINA AGATA DA SILVA FRANCA",
                        "JENYFER RAISSA DO NASCIMENTO COSTA",
                        "JESSIANE RIBEIRO CARNEIRO",
                        "KAUA GUILHERME CRUZ SILVA",
                        "KELRIANE BARROS DA COSTA",
                        "LUCIELE FLORENTINO PEREIRA DA SILVA",
                        "LUIZ EDUARDO LOURENCO FIGUEIRA MACEDO",
                        "MARCOS KAYRON ALBUQUERQUE ALVES",
                        "MARIA IONARA FERREIRA DOS SANTOS",
                        "MARIA SARAH LOPES DE BRITO",
                        "MAYCON DO NASCIMENTO PEREIRA",
                        "NARA LAUANE CARNEIRO FERREIRA",
                        "PEDRO HENRIQUE SOUSA MARTINS DA SILVA",
                        "PEDRO VINICIUS OLIVEIRA DOS ANGELOS",
                        "RYAN BARBOSA DE SOUSA",
                        "SUELEN CRISTINA FARIAS LEAL",
                        "VITORIA SANTOS DE OLIVEIRA SILVA",
                        "WELLY DE CASTRO BULHOES"
            ],
            "2º B": [
                        "AMANDA JASMYNE QUEIROZ GUIA",
                        "ANA BRUNA FELIX ACARCIO PEREIRA",
                        "ANA LAYS DE ALMEIDA",
                        "ANA LIVIA VASCONCELOS LOBO ROCHA",
                        "ANA VITORIA DE SOUZA AMARAL",
                        "CALEBE DA SILVA SANTOS",
                        "CECILIA SILVA OLIVEIRA",
                        "DEBORAH CARVALHO BEZERRA",
                        "GLENDA VITORIA GOMES DE LIVIA",
                        "GUILHERME BARBOSA LOURENCO",
                        "JOAO PIERRY ALVES DE OLIVEIRA",
                        "JOEL BARBOSA EVANGELISTA",
                        "KAROLYNNE DO NASCIMENTO V. C. ARAGAO",
                        "KERISSON ANDRADE AMORIM",
                        "KEYLLON VITORIO DE SOUZA AMBE",
                        "LUANA FONSECA MONTEIRO",
                        "LUCAS OLIVEIRA DE SOUZA",
                        "MARCOS VINICIUS SILVANO BATISTA",
                        "MARIA EDUARDA SANTANA RODRIGUES",
                        "MARIA HELLEN SOUSA BARROS",
                        "MIGUEL RONEY PEREIRA DUARTE",
                        "MOYSHES GOMES DO NASCIMENTO",
                        "NYKOLAS PEREIRA RIOS",
                        "PEDRO RIBEIRO HOLANDA",
                        "RIHANHA FERREIRA DOS REIS",
                        "RYANBERG FERREIRA BARBOSA DA SILVA",
                        "VARVARA OZEROVA",
                        "VICTOR GABRIEL LIMA DE SOUZA",
                        "YAN DHARLLYS MARTINS DO NASCIMENTO"
            ],
            "2º C": [
                        "AMANDA PEREIRA DA PENHA",
                        "ANA JULIA FERNANDES DE SOUSA",
                        "ANA LARA CORREIA LOPES",
                        "ARTHUR CARLOS DE ALMEIDA MOTTA",
                        "ARTHUR MONTENEGRO VENANCIO",
                        "BRENDA PEREIRA LIMA",
                        "ELLEN CRISTINA SILVA DOS SANTOS",
                        "EZEQUIEL GOMES DE SENA",
                        "FRANCISCA SAMILLY DA SILVA ARAUJO",
                        "GABRIEL ARAUJO SILVA",
                        "GABRIEL ONOFRE DE SOUSA MACIEL",
                        "JOSE ELIVELTON OLIVEIRA MAGALHAES",
                        "KAUA EMERSON LIMA MENEZES",
                        "KAYANNE RODRIGUES TEIXEIRA",
                        "KENCIANE OLIVEIRA DE SOUSA",
                        "MARIA ALICE RIBEIRO DA SILVA",
                        "MARIA APARECIDA SILVA DE SOUZA",
                        "MARIA EDUARDA CARIOLANO DE ARAUJO",
                        "MARIA FERNANDA SILVA DOS SANTOS FELIX",
                        "MARIA LAYANE MONTEIRO DE LIMA",
                        "MIGUEL ICARO DO NASCIMENTO TEIXEIRA DA SILVA",
                        "MIGUEL VASCONCELOS DINIZ",
                        "MIRELLA DE PAULA NASCIMENTO",
                        "PEDRO ADRIAN DA SILVA",
                        "PEDRO ITALO MAIA SOUSA",
                        "PEDRO LUCAS FEIJO",
                        "REBECA DIOGO SILVA MONTENEGRO",
                        "SAMYLLY RAYSSA DIAS ARAUJO",
                        "SUZANNA RAFAELLE COSTA S. DO NASCIMENTO",
                        "YURI ANDRADE DA MATA"
            ],
            "3º A": [
                        "ADRYAN DE PAULA ANDRADE",
                        "ALISSON COSTA DA SILVA",
                        "ANA BEATRIZ FURTADO TAVARES",
                        "ANA CAROLINE AIRES PEREIRA",
                        "ARIANI DA GUIA DOS SANTOS",
                        "BRUNO KENNEDY SOUSA SOARES",
                        "CAMILY DE OLIVEIRA COSTA",
                        "DANIELA CASTRO DE SOUZA",
                        "DIOGO ADRIAN TAVARES DE LIMA",
                        "EMANUELLE FERREIRA DE SOUSA",
                        "EMANUELLY DE CASSIA PINTO QUEIROZ",
                        "EMILY SOARES CUNHA GOMES",
                        "ISABELLA ALVES PEREIRA",
                        "IZABELLE CARVALHO SILVA",
                        "JEFERSON LAZANO MENDES DINIZ",
                        "JOAO NICOLAS DO NASCIMENTO",
                        "JOAO PEDRO SILVA DAS CHAGAS",
                        "KAYLA VITORIA MARQUES CAMPOS",
                        "KELTON MATEUS DE SOUSA NEVES",
                        "LARA RAYELE BORGES GOES",
                        "LAYS NAYRA GOMES FERREIRA",
                        "LETICIA BARBOSA TEIXEIRA",
                        "LIAM DE SOUSA FERREIRA",
                        "LUIDY RAYAN PEREIRA DA SILVA",
                        "LUIS DANIEL ALMEIDA DA SILVA",
                        "LUIZ GUSTAVO SANTANA DA MATA",
                        "MARIA FERNANDA SILVA SOUSA",
                        "PEDRO ERICK BEZERRA DE LIMA",
                        "PEDRO LUCAS LOPES MATIAS",
                        "SILAS DOS SANTOS ALMEIDA",
                        "YARLEI FERREIRA LOBAO",
                        "YASMIM LOURENCO DE FREITAS"
            ],
            "3º B": [
                        "ANA ALICE RODRIGUES DA SILVA",
                        "ANA CLARA DOS SANTOS DE PAULA",
                        "ANA KARINE ALBERTO SILVA",
                        "ANA LUIZA ALVES DE OLIVEIRA",
                        "ANDRE HENRIQUE DE SOUZA CAMPOS",
                        "ANGELA PATRICIA OLIVEIRA FRANCA LIMA",
                        "ANTONIA VANESSA LIMA DA MATA",
                        "CARLOS MISAEL DA SILVA FELIX",
                        "FLAVIO NOGUEIRA FILHO",
                        "FRANCISCO HUGO DA SILVA ARAUJO",
                        "GABRIEL VITOR ABREU MORAES",
                        "GUDSON MACEDO SANTANA",
                        "ISAAC ASSUNCAO RODRIGUES DE MATOS",
                        "JOAO MANOEL DIONIZIO DA SILVA",
                        "JOAO VICTOR SOUSA DA COSTA",
                        "JOSE ADRIEL DE SOUSA BERNARDO",
                        "JOSE RENAN ARAUJO LIMA CASTRO",
                        "KATHERINE LEITE BRAGA",
                        "KERLLON PAZ DA SILVA",
                        "LARA GABRIELLE RODRIGUES MORAIS",
                        "LETICIA HONORATO ALVES",
                        "LUCAS DOS SANTOS MATOKANOVIC",
                        "MARCIO MARLEY RIBEIRO DA SILVA",
                        "MARCUS YUAN PACHECO DE SOUSA",
                        "MARIA CLARA CALDAS RODRIGUES",
                        "MARIA EVELYN DA SILVA SABINO",
                        "ROMAN DUBOVIK",
                        "RYAN PEREIRA DE SOUSA",
                        "RYANNA FERREIRA RODRIGUES",
                        "SAMUEL MOREIRA FERREIRA",
                        "VERONICA DANIELA NUNEZ TORRES",
                        "WESLEI FERREIRA GOIS",
                        "YORRANA DA SILVA GONCALVES"
            ]
        },
        noturno: {
            "1º D": [   
                        "ANA GABRIELLY CRUZ PEREIRA",
                        "ANA LARA LOPES POLICARPO",
                        "ANA PAULA FERREIRA DA SILVA",
                        "CARLOS EDUARDO S. NASCIMENTO",
                        "CARLOS ICARO SOUSA BARRETO",
                        "CARMEN LUCIA DO NASCIMENTO SANTOS",
                        "CYNTHIA BIANCA RIBEIRO",
                        "DHEIMISON LEANDRO SILVA DE LIMA",
                        "FRANCISCA SILVANEIDE DA SILVA",
                        "GUSTAVO DE SOUSA RODRIGUES",
                        "JOAO GABRIEL DE CASTRO RIBEIRO",
                        "JOSE CAUA DOS SANTOS RODRIGUES",
                        "JOVANE HOLANDO GOMES",
                        "LAIANE DANIELE SILVA DE LIMA",
                        "LUAN RODRIGUES DE MORAIS",
                        "LUCIANO MIGUEL CORREIA DA SILVA",
                        "MARIA CLARA DA COSTA DOS SANTOS",
                        "MARIA EDUARDA PEREIRA MENDES",
                        "MARIA VANUSIA COELHO",
                        "MARINA RODRIGUES DE OLIVEIRA",
                        "NATANAEL LOBAO DA SILVA",
                        "RAYSSA SOUSA COSTA",
                        "ROSA MARIA DA SILVA",
                        "SAMUEL COSTA REBOUCAS",
                        "SAMYRA MARIA CAVALCANTE CRUZ",
                        "THAYSSA STHER FELIX REBOUCAS",
                        "TIFANNY DA SILVA MENDONCA",
                        "YASMIM PERUGI MENDONCA FRANCA",
                        "WILCKY SANTOS PEREIRA",
                        "YOHANA CORTEZ DE AZEVEDO"
            ],
            "2º D": [
                        "ANA LUIZA LOMBARDI MESQUITA",
                        "ARIEL LUCAS CARVALHO",
                        "ARIELY LETICIA LIMA OLIVEIRA",
                        "DOUGLAS MARCELO FERNANDES OLIVEIRA DE MELO",
                        "EMILY AZEVEDO DOS SANTOS",
                        "FRANCISCO DAVI RIBEIRO FREITAS",
                        "FRANCISCO WEVERTON DOS SANTOS",
                        "GABRIEL FREITAS DOS SANTOS",
                        "GABRIEL HENRIQUE FREITAS DE CARVALHO",
                        "GUILHERME GONCALVES SILVA",
                        "GUSTAVO SILVA OLIVEIRA",
                        "JOSE ROMULO FACUNDE DA SILVA",
                        "JULYAM NAYRIS GUEDES ALBUQUERQUE",
                        "KAUA CUNHA MATIAS",
                        "LEANDRO RAQUEL GOMES",
                        "LUANA FONSECA MONTEIRO",
                        "LUCAS HONORIO DE SOUSA",
                        "LUZIA KETTILY DIAS LOURENCO",
                        "MARIA SUYANE GOMES DA SILVA",
                        "NICOLE KETLIN DE OLIVEIRA",
                        "PEDRO GABRIEL MOREIRA DA COSTA",
                        "PEDRO YTALLO ALVES DE ARAUJO MOTA",
                        "RAY PEREIRA ROCHA NOGUEIRA",
                        "RAYANE BERNARDO DA SILVA SOARES",
                        "RIAN DE LIMA NASCIMENTO",
                        "SARA ROCHA DE SENA",
                        "TAINARA DE SOUZA"
            ],
            "3º C": [
                        "ADALBERTO",
                        "ANA LUISA PEREIRA DOS SANTOS",
                        "ARYANE SILVA DA GUIA",
                        "DANILO DOS SANTOS PEREIRA",
                        "EDUARDO DA SILVA MACEDO ARAUJO",
                        "ERIANA KEZIA NASCIMENTO RODRIGUES",
                        "FERNANDO ANTONIO MOTA DE SOUSA FILHO",
                        "FRANCISCA ELLEN CASTRO DOS SANTOS",
                        "GABRIEL VALENTIM BARROSO",
                        "ISRAEL LUIS DE PAULA ROCHA",
                        "IZABELE MARTINS DE SOUSA",
                        "JACO JOANICIO RAMOS DE SOUZA",
                        "KAUA CARDOSO DE OLIVEIRA",
                        "LUCAS DIOGO DE SOUZA",
                        "LUIZ DAVI CRUZ DA ROCHA",
                        "MARIA JAMILE DE SOUSA PEREIRA",
                        "MARIA REBECA SILVA DA CRUZ",
                        "MARIA TEREZA FELIX RODRIGUES",
                        "PAULO RENAN SILVA DE ALBUQUERQUE",
                        "PEDRO LUCAS DA SILVA GOMES",
                        "SAMUEL RODRIGUES GOMES",
                        "SARA DOS SANTOS HAYASHI",
                        "VICTORIA SANCHEZ DA SILVA ALVES",
                        "VITORIA CAROLINE MORAIS DE LIMA",
                        "WESLEY SANTANA FIRMINO"
            ]
        }
    };
